vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        book_images:
            uri_prefix: '%app.path.book_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.book_images%'

        me_images:
            uri_prefix: '%app.path.me_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.me_images%'
